version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: "bitnami/zookeeper:latest"
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka1:
    image: "bitnami/kafka:latest"
    container_name: kafka1
    restart: always
    ports:
      - "9091:9091"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9091
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
      - KAFKA_BROKER_ID=1
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092
      - ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper
  kafka2:
    image: "bitnami/kafka:latest"
    container_name: kafka2
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_BROKER_ID=2
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092
      - ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper
  producer:
    build: ./producer
    container_name: producer_kafka
    depends_on:
      - kafka1
      - kafka2
      - zookeeper
    volumes:
      - ./producer:/usr/src/app


  consumer:
    build: ./consumer
    container_name: consumer_kafka
    #deploy: 
      #replicas: 5
    depends_on:
      - kafka1
      - kafka2
      - zookeeper
      - producer
    volumes:
      - ./consumer:/usr/src/app

  



    